name: Build and Release Nebula APK

on:
  workflow_dispatch: # This adds the "One Click" button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      
      - name: Build Package
        run: |
          docker run --rm --platform linux/arm64 -v $(pwd):/home/builder/pkg alpine:latest sh -c "
            # 1. Install tools
            apk add alpine-sdk sudo
            adduser -D builder -G abuild
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            
            # 2. Setup the official abuild config directory
            mkdir -p /home/builder/.abuild
            echo '${{ secrets.ALPINELINUX_PRIVATE_KEY }}' > /home/builder/.abuild/signing.rsa
            echo 'PACKAGER_PRIVKEY=\"/home/builder/.abuild/signing.rsa\"' > /home/builder/.abuild/abuild.conf
            
            # 3. Set permissions
            chown -R builder:abuild /home/builder/pkg /home/builder/.abuild
            
            # 4. Execute build as builder user
            su builder -c '
              cd /home/builder/pkg
              abuild checksum
              abuild -r -P /home/builder/pkg/output
            '
          "

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/pkg/nebula-custom/aarch64/*.apk
          tag_name: v1.10.0-build-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
